### ISSUE TITLE
Can't compile, Xcode12.1, Catalina

### ISSUE THREAD

**Issue by olilarkin** [AudioKit/project-maroon-alpha#1]
Hey audio kit team,

I tried to compile this following instructions on my Catalina machine with Xcode 12.1, but it fails. I clone, pod install, and update the signing. When I try to build for simulator or device it fails hard!

Any ideas?

![image](https://user-images.githubusercontent.com/655662/97556572-9397f200-19d1-11eb-9d92-5e0938a7bcad.png)

**Comment by analogcode** [comment]
Instead of Pods, AudioKit will have to be added manually. 
Currently an issue w/ PODS. We will be updating the code. 
Thanks for your patience @olilarkin we really appreciate you diving in. 
–– Matt, @eljeff, @aure

**Comment by olilarkin** [comment]
I've got it compiling by manually copying in AudioKit and Disk, but it crashes on my iPad after the splash with something about DLYD. Doesn't crash on the simulator but no sound

**Comment by analogcode** [comment]
@olilarkin thanks for letting us know

**Comment by analogcode** [comment]
This should hopefully be fixed in the latest master w/ AudioKit included?

**Comment by aure** [comment]
Let us know if its not fixed
