### ISSUE TITLE
Successful launch on iPad, but no sound.

### ISSUE THREAD

**Issue by xcourier** [AudioKit/project-maroon-alpha#2]
As @olilarkin experienced, could not get the project to compile successfully under Xcode 12.1.
Downloaded a copy of Xcode 11.7 and installed AudioKit and Disk with the CocoaPods.
The project then complies fine and runs successfully on an iPad running iOS 12.x. 

The AUv3 also loads fine in GarageBand.

There seems to be no audio sent or produced  from the Stand Alone version of the App or the plugin however? 

Thanks for making this available!

**Comment by analogcode** [comment]
This should hopefully be fixed in the latest master w/ AudioKit included?

**Comment by olilarkin** [comment]
Yes it is fixed! You can Close the issue

**Comment by olilarkin** [comment]
Actually, I’m really sorry I’m not totally sure if it’s fixed or not. This
is a different issue to what I thought it was. I can build now since the
changes but I was having some problems with no sound, I’m not sure if it
was related to the app group which I had to modify
