### ISSUE TITLE
`LICENSE` file is missing

### ISSUE THREAD

**Issue by MaxDesiatov** [AudioKit/project-maroon-alpha#7]
It's unclear under which license this sample code is available, and if any of it can be cleanly reused from a legal perspective. A `LICENSE` file in the root of the repository would greatly help with this.

**Comment by analogcode** [comment]
Hi there! The code is MIT Licensed. 
There is a link to the license and banner at the top of the readme. 

<img width="304" alt="Screen Shot2" src="https://user-images.githubusercontent.com/2042313/120485706-97c62c80-c371-11eb-8c06-558c2fbf063b.png">

**Comment by MaxDesiatov** [comment]
Thanks, but the link points to the `ROMPlayer` project. There's no `LICENSE` file in this `AUv3-Example-App` repository though.
